"""book table

Revision ID: 232c1218bd26
Revises: d8935d3f8d4d
Create Date: 2022-03-11 10:41:59.320335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232c1218bd26'
down_revision = 'd8935d3f8d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('book_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'availability', type_='foreignkey')
    op.create_foreign_key(None, 'availability', 'book', ['book_id'], ['id'])
    op.drop_column('availability', 'book_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('book_title', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'availability', type_='foreignkey')
    op.create_foreign_key(None, 'availability', 'book', ['book_title'], ['title'])
    op.drop_column('availability', 'book_id')
    # ### end Alembic commands ###
