"""empty message

Revision ID: 9a56a0226283
Revises: 159ad13cd386
Create Date: 2022-03-11 13:17:40.419615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a56a0226283'
down_revision = '159ad13cd386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'availability', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availability', type_='foreignkey')
    # ### end Alembic commands ###
